name: Push and Deploy Serverless function
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v1
      with:
        token: ${{ secrets.YC_TOKEN }}
        bucket: 'newfaceof-telegram'
        function_id: 'd4en8jk0sdagi668nrqf'
        runtime: 'nodejs14'
        memory: '256'
        entrypoint: 'index.handler'
        environment: BOT_TOKEN=$BOT_TOKEN,CHANNEL_ID=$CHANNEL_ID
        source: '.'
