name: Build and push docker image
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Yandex Cloud CR Login Action for GH Actions
        uses: yc-actions/yc-cr-login@v1.0.0
        with:
          yc-sa-json-credentials: ${{ secrets.SA_BUILDER_PRIVATE_KEY }}
      - name: Build, tag, and push image to Yandex Cloud Container Registry
        env:
          CR_REPOSITORY: release/release-0.1/quiz
          YC_REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          export IMAGE_URI="cr.yandex/$YC_REGISTRY_ID/$CR_REPOSITORY:$IMAGE_TAG"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI


